version: '3.8'

services:
  redis-cache:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "13000:13000"
    volumes:
      - redis_cache:/data
      - ./redis_cache.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  
  redis-socketio:
    image: redis:alpine
    container_name: redis_socketio
    ports:
      - "12000:12000"
    volumes:
      - redis_socketio:/data
      - ./redis_socketio.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  
  redis-queue:
    image: redis:alpine
    container_name: redis_queue
    ports:
      - "11000:11000"
    volumes:
      - redis_queue:/data
      - ./redis_queue.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

volumes:
  redis_cache:
  redis_queue:
  redis_socketio: